services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    depends_on:
      - mongo
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo:27017/fixora
    ports:
      - "4000:4000"

volumes:
  mongo_data:
